# The Site Configuration

# Import the theme
# theme: jekyll-theme-chirpy # <--------------------------- ***IMPORTANT: THIS MUST BE COMMENTED OUT OR DELETED***

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/New_York

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: 1SecondLeads Blog - B2B Lead Gen Step by Step

tagline: Archive of our free SOPs, guides on B2B lead gen and sales, and case studies.

description: >-
  Archive of our free SOPs, guides on B2B lead gen and sales, and case studies.

# Fill in the protocol & hostname for your site.
# E.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://blog.1secondleads.com"

github:
  username: Bubaneshwar

twitter:
  username: twitter_username # Replace if you have one, or leave as is

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Ivan Malinovski
  email: ivan@1secondleads.com
  links:
    # The first element serves as the copyright owner's link
    - https://x.com/IvanMalinovski
    # - https://github.com/Bubaneshwar # Consider adding your GitHub profile here
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token
  fathom:
    id: # fill in your Fathom Site ID

# Page views settings
pageviews:
  provider: # Default from Chirpy, configure if needed

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light — Use the light color scheme
#     dark — Use the dark color scheme
#
theme_mode: # [light | dark] Default from Chirpy, set if you have a preference

# The CDN endpoint for media resources.
# Notice that once it is assigned, the CDN url
# will be added to all media resources (site avatar, posts' images, audio and video files) paths starting with '/'
#
# e.g. 'https://cdn.com'
cdn: "https://chirpy-img.netlify.app" # Default from Chirpy

# the avatar on sidebar, support local or CORS resources
avatar: "/commons/avatar.jpg" # Default from Chirpy, replace with your image path if you have one (e.g., /assets/img/avatar.png)

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image: # Default from Chirpy, set if you have a specific preview image

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  # Global switch for the post-comment system. Keeping it empty means disabled.
  provider: # Default from Chirpy, configure if you use comments (e.g., giscus)
  # The provider options are as follows:
  disqus:
    shortname:
  # utterances settings › https://utteranc.es/
  utterances:
    repo:
    issue_term:
  # Giscus options › https://giscus.app
  giscus:
    repo: # e.g., Bubaneshwar/blog.1secondleads.com
    repo_id: # fill this in after setting up Giscus
    category: # e.g., Announcements
    category_id: # fill this in
    mapping: pathname
    strict: 0
    input_position: bottom # or top
    lang: en # Or your preferred language for Giscus
    reactions_enabled: 1 # Or 0

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets: # Default from Chirpy
  self_host:
    enabled:
    env:

pwa: # Default from Chirpy
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

# The base URL of your site
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "↩︎"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/ # Tabs will be served at /<filename>/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude: # Using Chirpy's more comprehensive default exclude list
  - ".jekyll-cache"
  - ".jekyll-metadata"
  - ".idea"
  - ".vscode"
  - "package*.json"
  - "node_modules"
  - "rollup.config.js"
  - "tools"
  - "README.md"
  - "LICENSE"
  # Self-hosted static assets
  # - "assets/js/dist/" #
  # Others
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "*.gemspec"


jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-feed # Keeping this as it's standard for RSS, check if Chirpy uses it.
  # Add any other jekyll- GEMS from the gemspec if they were missed and look like active plugins.
  # For example, Chirpy's gemspec might also list jekyll-gist or jekyll-redirect-from.
  # If so, add them here. For now, this list covers what's explicitly in your gemspec + feed.